[package]
name = "flownote-tauri"
version = "0.1.0"
edition = "2024"

[dependencies]
flownote-core = { version = "0.1.0", path = "../flownote-core" }
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
specta = { version = "=2.0.0-rc.22", features = ["derive"] }
specta-typescript = "0.0.9"
tauri = "2"
tauri-specta = { version = "=2.0.0-rc.21", features = ["derive", "typescript"] }
