[workspace]
resolver = "2"
members = [
  "crates/flownote-core",
  "crates/flownote-electron",
  "crates/flownote-tauri",
  "crates/flownote-sync",
  "apps/tauri/src-tauri",
]

# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
